### PR TITLE
Update Bundler to 2.5.21 and truffleruby to 24.1.0

### PR DESCRIPTION
**Pull request by deivid-rodriguez**
## What was the end-user or developer problem that led to this PR?

Nothing, I saw a PR will failing CI and wondering if updating Bundler will fix it. I don't think it will, to be honest, but upgrading doesn't hurt.

## What is your fix for the problem, implemented in this PR?

Upgrade Bundler.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by simi** [comment]
:window: :boom: Any idea what's happening on CI?

**Comment by deivid-rodriguez** [comment]
I thought I had fixed it, but apparently I did not. Looking into it.

**Comment by deivid-rodriguez** [comment]
A bit of back and forth looking for the culprit since there are many moving parts for mswin, but I believe https://github.com/MSP-Greg/ruby-loco/pull/15 should get our CI back on track.

**Review by segiddins — APPROVED** [review]

**Comment by deivid-rodriguez** [comment]
Everything is green now!

**Pull request merged**
