### PR TITLE
Update bundler & parser

### PR DESCRIPTION
**Pull request by segiddins**
## What was the end-user or developer problem that led to this PR?

Keeping a bunch of things up to date, particularly making sure things work with Ruby 3.3.

## What is your fix for the problem, implemented in this PR?

Update stuff.

## Make sure the following tasks are checked

- [x] Describe the problem / feature
- [ ] Write [tests](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#tests) for features and bug fixes
- [x] Write code to solve the problem
- [x] Make sure you follow the [current code style](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#code-formatting) and [write meaningful commit messages without tags](https://github.com/rubygems/rubygems/blob/master/bundler/doc/development/PULL_REQUESTS.md#commit-messages)

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
I think this can be rebased now to only update parser and it should be fine 👍.

**Comment by deivid-rodriguez** [comment]
@segiddins Mind if I rebase this one?

**Comment by segiddins** [comment]
go for it!

**Comment by deivid-rodriguez** [comment]
I ended up updating a few more things, it should be ready now.

**Pull request merged**
